# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-24.04' 

variables:
- group: 'github-access'
- name: 'containerRegistry'
  value: 'acr-morphic'
- name: 'repository'
  value: 'morphic-api-server'
- name: 'tag'
  value: '$(Build.BuildNumber)'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# 
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# TODO:
# - detect the branch (master, develop or prod)
# - create a tag prefix for the docker tag, based on the branch
#   master -> [no prefix]
#   prod -> [no prefix]
#   develop -> dev-
# - choose the container registry, based on the branch
#   master -> acr-morphic
#   prod -> dockerhub-raisingthefloor
#   develop -> acr-morphicdev
# - NOTE: we may want to create an "acr-morphicpr" container registry as well, and send any docker images there for PR check-ins (and then launch a temporary site off of a pr.morphic.org subdomain)
# - finally: create a mechanism (during dev and production deployment) to delete any container images from the registry which are older than the image we are replacing (i.e. only keep the current one and the new one)

stages:
- stage: Docker
  displayName: Build and push Docker image
  jobs:
  - job: DockerBuildAndPush
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        containerRegistry: $(containerRegistry)
        dockerfile: './Dockerfile'
        repository: $(repository)
        tags: $(tag)
    - task: Docker@2
      displayName: Log in to container registry
      inputs:
        command: login
        containerRegistry: $(containerRegistry)
    - task: Docker@2
      displayName: Push docker image
      inputs:
        command: push
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        tags: $(tag)
    - task: Docker@2
      displayName: Log out of container registry
      inputs:
        command: logout
        containerRegistry: $(containerRegistry)

