# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-20.04

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# 
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# TODO:
# - detect the branch (master, develop or prod)
# - create a tag prefix for the docker tag, based on the branch
#   master -> [no prefix]
#   prod -> [no prefix]
#   develop -> dev-
# - choose the container registry, based on the branch
#   master -> acr-morphic
#   prod -> dockerhub-raisingthefloor
#   develop -> acr-morphicdev
# - NOTE: we may want to create an "acr-morphicpr" container registry as well, and send any docker images there for PR check-ins (and then launch a temporary site off of a pr.morphic.org subdomain)
# - finally: create a mechanism (during dev and production deployment) to delete any container images from the registry which are older than the image we are replacing (i.e. only keep the current one and the new one)

stages:
  - stage: Docker
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              command: build
              containerRegistry: acr-morphic
              repository: morphic-api-server
              tags: $(Build.BuildNumber)
          - task: Docker@2
            displayName: Log in to container registry
            inputs:
              command: login
              containerRegistry: acr-morphic
          - task: Docker@2
            displayName: Push docker image
            inputs:
              command: push
              containerRegistry: acr-morphic
              repository: morphic-api-server
              tags: $(Build.BuildNumber)
          - task: Docker@2
            displayName: Log out of container registry
            inputs:
              command: logout
              containerRegistry: acr-morphic

