db.AuthToken.find()
db.AuthToken.remove({})
db.BadPasswordLockout.find()
db.BadPasswordLockout.remove({})
db.KeyCredential.find()
db.KeyCredential.remove({})
db.OneTimeToken.find()
db.OneTimeToken.remove({})
db.Preferences.find()
db.Preferences.remove({})
db.User.find()
db.User.remove({})
db.UsernameCredential.find()
db.UsernameCredential.remove({})

