{
 "title": "MorphicServer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_duration_count) by (method, path, status)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(dotnet_total_memory_bytes/1024/1024) by (instance)"
    }
   ]
  },
  {
   "title": "Emails Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(email_send_duration_count) by (type, success)"
    }
   ]
  },
  {
   "title": "Error and Warn Logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_log_level_count{level!~\"Information|Debug\"}"
    }
   ]
  }
 ]
}